name: Daily Kimchi Gold Collect

on:
  schedule:
    # 매일 오전 90시(한국시간, KST=UTC+9) 실행 (UTC 기준 0 10 * * *)
    - cron: '0 1 * * *'
  workflow_dispatch:  # 수동 실행도 가능하게 함

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run web scraper and plot results
        run: |
          uv run python src/kimchi_gold/collect_price.py
          uv run python src/kimchi_gold/plot.py

      - name: Commit and push changes
        run: |
          git config --local user.email "deepthough@postech.ac.kr"
          git config --local user.name "Auto_Scraping"
          git add data/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update scraped data"
            git push
          else
            echo "No changes to commit in data/. Skipping commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
